content/team.en.md
It was removed accidentally in #15.
=> Bring back team page

static/googlebcbc6ddd5c481729.html
on Canen request, simple html file to verify website ownership for google
=> Added google verification html file

content/download.en.md
Creates a new "Third Party Wallets" section.
=> Add exodus wallet to download page. Fixes #17

themes/elate/layouts/partials/hero.html
Friendly Header Image Update Link
=> Update Link For Header Image (Friendly)

content/mine.en.md
There's plenty of guides -> There are plenty of guides
=> Fix grammar mistake in mining page

content/mine.en.md
Updated link to new OCM image without BG
=> Updated link to new OCM image

themes/elate/static/css/style.css
From trial green to logo green
=> Fixed Social Link Color

i18n/en.toml
=> Update "Exchange" to "Trading"

content/trading.en.md
=> Added Vertpig to the exchange listings

themes/elate/static/css/style.css
=> Reduce home page fontsize

config.toml
Replace Alex Photo with placehoder
=> Remove Alex Photo

config.toml
Put emphasis on community first
=> Move Community to First Spot

config.toml, i18n/en.toml
This PR resolves #65 by removing the home menu item.
=> Removes the 'home' menu item.

config.toml, i18n/en.toml
This PR resolves #67 by promoting the "Vertcoin Community" `about.item` to the top of the list. In addition it adds social media icons to make this item consistent with the other team member items.
=> Promote the Vertcoin Community on the team page.

i18n/en.toml
Update header to put more emphasis on fundamentals focus.
Fix spelling.
=> Update Header call to action

i18n/en.toml
Fix Bryan Grammar / Tidy - Grammatical Changes
=> Fix Bryan Grammar / Tidy

i18n/en.toml
=> How -> Premise

config.toml
Update Filepath JPG -> PNG (Wrong Green) Development profile page
=> Update Filepath JPG -> PNG (Wrong Green)

i18n/en.toml
Shorten phrasing, to be your own bank from "Your Bank, Your Control etc"
=> Change LitWallet Title

i18n/en.toml
Better outlines Vertcoin as a whole, and is less vague.
=> Change First Paragraph In Premise

i18n/en.toml
Switched specs for what is mining
=> Update Premise Section link

config.toml
=> Update Link for How section

i18n/en.toml
Original goal, date established, bitcoin and litecoin comparison.
=> Update 2nd Paragraph - Premise section

i18n/en.toml
Decentralised Mining word change
=> Fair To Mine Forever -> Decentralised Mining

i18n/en.toml
=> Premise -> Our Goal

content/merchants.en.md
Make headings larger, consistent with other pages
=> Changes to heading size

themes/elate/static/css/style.css
=> Unhide first nav item mobile

content/merchants.en.md
Fix Food Heading Size - Missed in previous resizing
=> Fix Food Heading Size

content/download.en.md
Update Wording - 'Don't FALL into any other'
=> Update Wording - 'Don't FALL into any other'

i18n/en.toml
Added OCM relevance to the title, decentralised mining / usable by the masses.
Added LIT relation
=> Updated Titles to be more specific

i18n/en.toml
Shows the 'why' behind litbox - Changed Description
=> Shows the 'why' behind litbox

i18n/en.toml
=> Highlighted key aspects explaining litbox

i18n/en.toml
Section wording was too bolded. Reduced coverage.
=> Reduce Bolding - Lit section

i18n/en.toml
Too Specific, users may not understand terminology. One-Click Miner is fairly self explanatory... possibly add something in the second paragraph
=> Removed User Centric

i18n/en.toml
=> Lit Section - Remove Bloat Wording

themes/elate/layouts/partials/head.html
Update Meta Info / Disable Google Font link
=> Update Meta Info / Disable Google Font link

themes/elate/static/css/style.css
Hide Subtitle Litbox Section, too messy
=> Hide Subtitle Litbox Section

i18n/en.toml
Now covers all sections or decentralisation contract
=> Redo Social Contract Section

i18n/en.toml
Specialized -> Specialised / Mining Section
=> Specialized -> Specialised

i18n/en.toml
Capitalization -> Capitalisation fix
=> Capitalization -> Capitalisation

content/accept-vertcoin.en.md
=> Missing S from 'Gives'

i18n/en.toml
Specify Usability For Miner Header Button
=> Specify Usability For Download Miner Header Button

content/merchants.en.md
https://twitter.com/RSJackpot/status/983802871912296448
=> New merchant RSJackpot

themes/elate/layouts/partials/hero.html
Hero Button Width Changes - to match content changes
=> Hero Button Width Changes

i18n/en.toml
Decentralised Mining Network - heading change
=> Decentralised Mining Network

content/mine.en.md
=> OCM crop fix

i18n/en.toml
Accept Vertcoin Payments -> Accept Vertcoin
Makes room for litbox CAD
=> Accept Vertcoin Payments -> Accept Vertcoin

i18n/en.toml
More emphasis on Goal - Bolding
=> More emphasis on Goal Section

content/download.en.md
0.12 VTC Core -> 0.13 VTC Core Download links
=> 0.12 VTC Core -> 0.13 VTC Core

content/download.en.md
0.12 VTC Core -> 0.13 VTC Core Download links
Fixed - Location Change /
vertcoin -> vertcoin-project
=> Links Fixed, Locations Changed

content/download.en.md
=> Remove Exodus Wallet

content/download.en.md
Update Electrum Download Links to 3.1.2
=> Update Electrum Download Links to 3.1.2

content/mine.en.md
=> Fix OCM Link

themes/elate/static/css/style.css
=> Wrapper P (23px font to 21px)

themes/elate/static/css/style.css
Adjust Atomic Swap Image to fit text size
=> Adjust Atomic Swap Image to fit text size

i18n/en.toml
Learn More links to technical specs for now / will link to consensus area
Added Button
Changed Section Title from "Creating A Balanced System"
=> What Is Consensus Section

content/merchants.en.md
Fix 'Printing' to Larger Heading
=> Fix 'Printing' to Larger Heading

i18n/en.toml
" to ', hugo syntax styling (What is Consensus)
=> " to ', hugo syntax styling (What Is Consensus)

i18n/en.toml
" to ' class change hugo (what is consensus)
=> " to ' class change hugo (what is consensus)

themes/elate/layouts/partials/hero.html
Mismatch <div> <a> tag 
Fixes surrounding box area of button (2nd button)
=> Mismatch <div> <a> tag (hero area)

config.toml, i18n/de.toml
Hey @Vertcoin-Project community, :smiley:
*This is my first commit and my first pull request here at Vercoin.* :tada:
**I translated the main website content from *English* ([`en.toml`](https://github.com/vertcoin-project/vertcoin-website/blob/master/i18n/en.toml)) to *German* (`de.toml`).**
*Yours Sincerely,*
[**Suriyaa Sundararuban**](https://suriyaa.tk/) <a href="https://github.com/SuriyaaKudoIsc"><img src="https://assets-cdn.github.com/images/icons/emoji/octocat.png" alt="GitHub Developer" width="18" height="18" /></a> <a href="https://vertcoin.org/team/"><img src="https://cdn.discordapp.com/emojis/430323443918176256.png" alt="Future Official Vertcoin Developer?" width="20" height="20" /></a>
=> Support German (de) language

COPYING
Hi, :smiley:
I created the `COPYING` file. ✏️ 
--[**Suriyaa Sundararuban**](https://suriyaa.tk/) <a href="https://github.com/SuriyaaKudoIsc"><img src="https://assets-cdn.github.com/images/icons/emoji/octocat.png" alt="GitHub Developer" width="18" height="18" /></a> <a href="https://vertcoin.org/team/"><img src="https://cdn.discordapp.com/emojis/430323443918176256.png" alt="Future Official Vertcoin Developer?" width="20" height="20" /></a> (***Donate some VTC:*** `3GzoCsknkwM7ZSqKYYsUaz7wCMnFbCN6uh`)
=> Add COPYING / License file

config.toml, i18n/de.toml, i18n/en.toml, i18n/fr.toml
To @CryptoPlankton, :smiley:
I added myself to the Vertcoin team site. ➕ 👨‍💻  
--[**Suriyaa Sundararuban**](https://suriyaa.tk/) <a href="https://github.com/SuriyaaKudoIsc"><img src="https://assets-cdn.github.com/images/icons/emoji/octocat.png" alt="GitHub Developer" width="18" height="18" /></a> <a href="https://vertcoin.org/team/"><img src="https://cdn.discordapp.com/emojis/430323443918176256.png" alt="Future Official Vertcoin Developer?" width="20" height="20" /></a> (***Donate some VTC:*** `3GzoCsknkwM7ZSqKYYsUaz7wCMnFbCN6uh`)
=> Add Suriyaa to Vertcoin Team
